### ISSUE TITLE
Referring to issue no #57 and #16, This crash comes with importAsExternalLink as well. Please guide

### ISSUE THREAD

**Issue by Eeshdaya** [ngageoint/geopackage-android#67]
Please fill out as much known and relevant information as possible.

#### Version Information:

  * GeoPackage Android Version: 4.0.0
  * GeoPackage Android Source: (e.g. Central Repository / Bintray, Release, Source Code Build) central repo
  * Device or Emulator: device
  * Android Studio Version: 4.1.3
  * Android Version Number: 9 
  * Android SDK Version: 29
  * Platform & OS: Android
  * Other Relevant Libraries:

#### Expected Results:

  * What did you expect to happen? - import geopackage file with given path

#### Observed Results:

  * What happened instead?
  I get java.lang.ExceptionInInitializerError, saying it could not open some file in app/data/.../base.apk
  
  * How often does this occur? Frequent, every time app starts from fresh.

#### Output:

  * Any logs, errors, or output messages?
  * 
2021-05-01 17:38:26.577 28181-28181/com.sixsimplex.revelo E/System: Unable to open zip file: /data/app/com.sixsimplex.revelo-qcn96uwbyhmtAMG8qGYDDg==/base.apk
2021-05-01 17:38:26.583 28181-28181/com.sixsimplex.revelo E/System: java.io.FileNotFoundException: File doesn't exist: /data/app/com.sixsimplex.revelo-qcn96uwbyhmtAMG8qGYDDg==/base.apk
        at java.util.zip.ZipFile.<init>(ZipFile.java:215)
        at java.util.zip.ZipFile.<init>(ZipFile.java:152)
        at java.util.jar.JarFile.<init>(JarFile.java:160)
        at java.util.jar.JarFile.<init>(JarFile.java:97)
        at libcore.io.ClassPathURLStreamHandler.<init>(ClassPathURLStreamHandler.java:47)
        at dalvik.system.DexPathList$Element.maybeInit(DexPathList.java:702)
        at dalvik.system.DexPathList$Element.findResource(DexPathList.java:729)
        at dalvik.system.DexPathList.findResource(DexPathList.java:508)
        at dalvik.system.BaseDexClassLoader.findResource(BaseDexClassLoader.java:169)
        at java.lang.ClassLoader.getResource(ClassLoader.java:793)
        at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:987)
        at java.lang.Class.getResourceAsStream(Class.java:2211)
        at mil.nga.geopackage.property.GeoPackageProperties.initializeConfigurationProperties(GeoPackageProperties.java:262)
        at mil.nga.geopackage.property.GeoPackageProperties.getProperty(GeoPackageProperties.java:50)
        at mil.nga.geopackage.property.GeoPackageProperties.getProperty(GeoPackageProperties.java:82)
        at mil.nga.geopackage.property.GeoPackageProperties.getProperty(GeoPackageProperties.java:68)
        at mil.nga.geopackage.extension.CrsWktExtension.<clinit>(CrsWktExtension.java:39)
        at mil.nga.geopackage.GeoPackageCoreImpl.getSpatialReferenceSystemDao(GeoPackageCoreImpl.java:788)
        at mil.nga.geopackage.validate.GeoPackageValidate.hasMinimumTables(GeoPackageValidate.java:132)
        at mil.nga.geopackage.validate.GeoPackageValidate.validateMinimumTables(GeoPackageValidate.java:150)
        at mil.nga.geopackage.GeoPackageManagerImpl.open(GeoPackageManagerImpl.java:894)
        at mil.nga.geopackage.GeoPackageManagerImpl.importGeoPackageAsExternalLink(GeoPackageManagerImpl.java:1167)
        at mil.nga.geopackage.GeoPackageManagerImpl.importGeoPackageAsExternalLink(GeoPackageManagerImpl.java:1115)
        at mil.nga.geopackage.GeoPackageManagerImpl.importGeoPackageAsExternalLink(GeoPackageManagerImpl.java:1107)
        at com.sixsimplex.revelo.geopackage.geopackage.GeoPackageManagerAgent.getMetaGeoPackage(GeoPackageManagerAgent.java:78)
        at com.sixsimplex.revelo.geopackage.tableUtil.EntitiesTable.getDao(EntitiesTable.java:55)
        at com.sixsimplex.revelo.geopackage.tableUtil.EntitiesTable.getFeatureLayers(EntitiesTable.java:72)
        at com.sixsimplex.revelo.home.presenter.HomePresenter.createEntityListData(HomePresenter.java:710)
        at com.sixsimplex.revelo.home.HomeActivity.callHomeUi(HomeActivity.java:245)
        at com.sixsimplex.revelo.home.HomeActivity.successMessage(HomeActivity.java:464)
        at com.sixsimplex.revelo.home.presenter.HomePresenter.checkDataDownloadScenario(HomePresenter.java:263)
        at com.sixsimplex.revelo.home.presenter.HomePresenter.onPresenterHome(HomePresenter.java:137)
        at com.sixsimplex.revelo.home.HomeActivity.initComponent(HomeActivity.java:216)
        at com.sixsimplex.revelo.home.HomeActivity.onCreate(HomeActivity.java:144)
        at android.app.Activity.performCreate(Activity.java:7272)
        at android.app.Activity.performCreate(Activity.java:7263)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3163)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3318)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2022)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7147)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:511)
    	at com.android.internal.os.ZygoteInit.main(ZygoteI
2021-05-01 17:38:26.583 28181-28181/com.sixsimplex.revelo E/GeoPackageProperties: Failed to load properties, file not found: geopackage.properties
2021-05-01 17:38:26.590 28181-28181/com.sixsimplex.revelo D/AndroidRuntime: Shutting down VM
2021-05-01 17:38:26.596 28181-28181/com.sixsimplex.revelo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sixsimplex.revelo, PID: 28181
    java.lang.ExceptionInInitializerError
        at mil.nga.geopackage.GeoPackageCoreImpl.getSpatialReferenceSystemDao(GeoPackageCoreImpl.java:788)
        at mil.nga.geopackage.validate.GeoPackageValidate.hasMinimumTables(GeoPackageValidate.java:132)
        at mil.nga.geopackage.validate.GeoPackageValidate.validateMinimumTables(GeoPackageValidate.java:150)
        at mil.nga.geopackage.GeoPackageManagerImpl.open(GeoPackageManagerImpl.java:894)
        at mil.nga.geopackage.GeoPackageManagerImpl.importGeoPackageAsExternalLink(GeoPackageManagerImpl.java:1167)
        at mil.nga.geopackage.GeoPackageManagerImpl.importGeoPackageAsExternalLink(GeoPackageManagerImpl.java:1115)
        at mil.nga.geopackage.GeoPackageManagerImpl.importGeoPackageAsExternalLink(GeoPackageManagerImpl.java:1107)
        at com.sixsimplex.revelo.geopackage.geopackage.GeoPackageManagerAgent.getMetaGeoPackage(GeoPackageManagerAgent.java:78)
        at com.sixsimplex.revelo.geopackage.tableUtil.EntitiesTable.getDao(EntitiesTable.java:55)
        at com.sixsimplex.revelo.geopackage.tableUtil.EntitiesTable.getFeatureLayers(EntitiesTable.java:72)
        at com.sixsimplex.revelo.home.presenter.HomePresenter.createEntityListData(HomePresenter.java:710)
        at com.sixsimplex.revelo.home.HomeActivity.callHomeUi(HomeActivity.java:245)
        at com.sixsimplex.revelo.home.HomeActivity.successMessage(HomeActivity.java:464)
        at com.sixsimplex.revelo.home.presenter.HomePresenter.checkDataDownloadScenario(HomePresenter.java:263)
        at com.sixsimplex.revelo.home.presenter.HomePresenter.onPresenterHome(HomePresenter.java:137)
        at com.sixsimplex.revelo.home.HomeActivity.initComponent(HomeActivity.java:216)
        at com.sixsimplex.revelo.home.HomeActivity.onCreate(HomeActivity.java:144)
        at android.app.Activity.performCreate(Activity.java:7272)
        at android.app.Activity.performCreate(Activity.java:7263)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3163)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3318)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2022)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7147)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:511)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
     Caused by: java.lang.RuntimeException: Property not found: geopackage.extensions.crs_wkt
        at mil.nga.geopackage.property.GeoPackageProperties.getProperty(GeoPackageProperties.java:54)
        at mil.nga.geopackage.property.GeoPackageProperties.getProperty(GeoPackageProperties.java:82)
        at mil.nga.geopackage.property.GeoPackageProperties.getProperty(GeoPackageProperties.java:68)
        at mil.nga.geopackage.extension.CrsWktExtension.<clinit>(CrsWktExtension.java:39)
        at mil.nga.geopackage.GeoPackageCoreImpl.getSpatialReferenceSystemDao(GeoPackageCoreImpl.java:788) 
        at mil.nga.geopackage.validate.GeoPackageValidate.hasMinimumTables(GeoPackageValidate.java:132) 
        at mil.nga.geopackage.validate.GeoPackageValidate.validateMinimumTables(GeoPackageValidate.java:150) 
        at mil.nga.geopackage.GeoPackageManagerImpl.open(GeoPackageManagerImpl.java:894) 
        at mil.nga.geopackage.GeoPackageManagerImpl.importGeoPackageAsExternalLink(GeoPackageManagerImpl.java:1167) 
        at mil.nga.geopackage.GeoPackageManagerImpl.importGeoPackageAsExternalLink(GeoPackageManagerImpl.java:1115) 
        at mil.nga.geopackage.GeoPackageManagerImpl.importGeoPackageAsExternalLink(GeoPackageManagerImpl.java:1107) 
        at com.sixsimplex.revelo.geopackage.geopackage.GeoPackageManagerAgent.getMetaGeoPackage(GeoPackageManagerAgent.java:78) 
        at com.sixsimplex.revelo.geopackage.tableUtil.EntitiesTable.getDao(EntitiesTable.java:55) 
        at com.sixsimplex.revelo.geopackage.tableUtil.EntitiesTable.getFeatureLayers(EntitiesTable.java:72) 
        at com.sixsimplex.revelo.home.presenter.HomePresenter.createEntityListData(HomePresenter.java:710) 
        at com.sixsimplex.revelo.home.HomeActivity.callHomeUi(HomeActivity.java:245) 
        at com.sixsimplex.revelo.home.HomeActivity.successMessage(HomeActivity.java:464) 
        at com.sixsimplex.revelo.home.presenter.HomePresenter.checkDataDownloadScenario(HomePresenter.java:263) 
        at com.sixsimplex.revelo.home.presenter.HomePresenter.onPresenterHome(HomePresenter.java:137) 
        at com.sixsimplex.revelo.home.HomeActivity.initComponent(HomeActivity.java:216) 
        at com.sixsimplex.revelo.home.HomeActivity.onCreate(HomeActivity.java:144) 
        at android.app.Activity.performCreate(Activity.java:7272) 
        at android.app.Activity.performCreate(Activity.java:7263) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3163) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3318) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2022) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:224) 
        at android.app.ActivityThread.main(ActivityThread.java:7147) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:511) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876) 
#### Steps to Reproduce:

  1. Step One
  2. Step Two
  3. ...

#### Relevant Code:

```java
// Code to reproduce the problem?
```

#### Test Files:

  * Links to any files needed for testing?

#### Additional Information:

  * Any additional configuration, data, or information that might help with the issue?
 This happens everytime I start the app from rest. When I run app for second time, it goes fine

**Comment by bosborn** [comment]
This appears to be a class loading issue with your app initialization, not with that specific import method.

Your stack trace points to a problem [loading a property resource file in GeoPackageProperties](https://github.com/ngageoint/geopackage-core-java/blob/cd3ffea29f85dca861c043bae47b064d9684235e/src/main/java/mil/nga/geopackage/property/GeoPackageProperties.java#L261) from the Java core library.

```
InputStream in = GeoPackageProperties.class
		.getResourceAsStream("/" + PropertyConstants.PROPERTIES_FILE);
```
Where:
`"/" + PropertyConstants.PROPERTIES_FILE` == `“/geopackage.properties”`

Your Error within BaseDexClassLoader:
`2021-05-01 17:38:26.583 28181-28181/com.sixsimplex.revelo E/System: java.io.FileNotFoundException: File doesn't exist: /data/app/com.sixsimplex.revelo-qcn96uwbyhmtAMG8qGYDDg==/base.apk`

Some InputStream property example values while successfully running the [testImportAsExternalLink test](https://github.com/ngageoint/geopackage-android/blob/547a11cf9041766a781330f99e3f30d7c9d6f900/geopackage-sdk/src/androidTest/java/mil/nga/geopackage/test/GeoPackageManagerTest.java#L555):
```
file:/data/app/~~eKnGSRtbYB3H4u2IjexkLg==/mil.nga.geopackage.test-83AuzCRndZPUMM9m-aPYgw==/base.apk
jar:file:/data/app/~~eKnGSRtbYB3H4u2IjexkLg==/mil.nga.geopackage.test-83AuzCRndZPUMM9m-aPYgw==/base.apk!/geopackage.properties
```

Have you tried [enabling multidex](https://stackoverflow.com/a/34397863)?

**Comment by Eeshdaya** [comment]
> This appears to be a class loading issue with your app initialization, not with that specific import method.
> 
> Your stack trace points to a problem [loading a property resource file in GeoPackageProperties](https://github.com/ngageoint/geopackage-core-java/blob/cd3ffea29f85dca861c043bae47b064d9684235e/src/main/java/mil/nga/geopackage/property/GeoPackageProperties.java#L261) from the Java core library.
> 
> ```
> InputStream in = GeoPackageProperties.class
> 		.getResourceAsStream("/" + PropertyConstants.PROPERTIES_FILE);
> ```
> 
> Where:
> `"/" + PropertyConstants.PROPERTIES_FILE` == `“/geopackage.properties”`
> 
> Your Error within BaseDexClassLoader:
> `2021-05-01 17:38:26.583 28181-28181/com.sixsimplex.revelo E/System: java.io.FileNotFoundException: File doesn't exist: /data/app/com.sixsimplex.revelo-qcn96uwbyhmtAMG8qGYDDg==/base.apk`
> 
> Some InputStream property example values while successfully running the [testImportAsExternalLink test](https://github.com/ngageoint/geopackage-android/blob/547a11cf9041766a781330f99e3f30d7c9d6f900/geopackage-sdk/src/androidTest/java/mil/nga/geopackage/test/GeoPackageManagerTest.java#L555):
> 
> ```
> file:/data/app/~~eKnGSRtbYB3H4u2IjexkLg==/mil.nga.geopackage.test-83AuzCRndZPUMM9m-aPYgw==/base.apk
> jar:file:/data/app/~~eKnGSRtbYB3H4u2IjexkLg==/mil.nga.geopackage.test-83AuzCRndZPUMM9m-aPYgw==/base.apk!/geopackage.properties
> ```
> 
> Have you tried [enabling multidex](https://stackoverflow.com/a/34397863)?

enabling multidex worked! Thanks!

**Comment by Eeshdaya** [comment]
Sorry, It wasn't fixed by multidex enabling. Please guide
